language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install pytest
  - pip install https://software.ecmwf.int/wiki/download/attachments/56664858/ecmwf-api-client-python.tgz

script: 
  - make test_travis
